export const registry = {
  js: {
    extensions: ['.js', '.mjs', '.cjs', '.ts', '.tsx'],
    linter: 'ESLint',
    configFile: 'eslint.config.mjs',
    workflowFile: 'lint-js.yml',
    marker: '// scaffold-linter: js',
    metricsOnly: false,
  },
  python: {
    extensions: ['.py'],
    linter: 'Ruff',
    configFile: 'ruff.toml',
    workflowFile: 'lint-python.yml',
    marker: '# scaffold-linter: python',
    metricsOnly: false,
  },
  go: {
    extensions: ['.go'],
    linter: 'golangci-lint',
    configFile: '.golangci.yml',
    workflowFile: 'lint-go.yml',
    marker: '# scaffold-linter: go',
    metricsOnly: false,
  },
  rust: {
    extensions: ['.rs'],
    linter: 'Clippy',
    configFile: 'clippy.toml',
    workflowFile: 'lint-rust.yml',
    marker: '# scaffold-linter: rust',
    metricsOnly: false,
  },
  ruby: {
    extensions: ['.rb'],
    linter: 'RuboCop',
    configFile: '.rubocop.yml',
    workflowFile: 'lint-ruby.yml',
    marker: '# scaffold-linter: ruby',
    metricsOnly: false,
  },
  shell: {
    extensions: ['.sh', '.bash'],
    linter: 'Shellcheck',
    configFile: '.shellcheckrc',
    workflowFile: 'lint-shell.yml',
    marker: '# scaffold-linter: shell',
    metricsOnly: false,
  },
  elixir: {
    extensions: ['.ex', '.exs'],
    linter: 'Credo',
    configFile: '.credo.exs',
    workflowFile: 'lint-elixir.yml',
    marker: '# scaffold-linter: elixir',
    metricsOnly: false,
  },
  zig: {
    extensions: ['.zig'],
    linter: 'zig fmt',
    workflowFile: 'lint-zig.yml',
    marker: '# scaffold-linter: zig',
    metricsOnly: true,
  },
  mojo: {
    extensions: ['.mojo'],
    linter: 'mojo format',
    workflowFile: 'lint-mojo.yml',
    marker: '# scaffold-linter: mojo',
    metricsOnly: true,
  },
};
